[colors.primary]
background = "#002b36"

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
dynamic_title = true
startup_mode = "Maximized"
decorations = "buttonless"

[window.padding]
x = 8
y = 8
